# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80cb5a836b76bc8875cae0381124d15be1d70eb74339cf2c72a7547a6fd487baaeafe65870803f112a12d50e84f62bc83684c30682afd67ab09645ef244cd670

test:
  secret_key_base: c81654fced7a40208e08c34098f064fcaf16f53f0211ca79f9628747a18b85ea9a9cfe1b4b79aaf156d08693be1c2b5b149df6db79a08ed9fe0e4c0c3d4bbe71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
